services:
  web:
    image: medtrack:0.1
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: "changeme"
      MONGO_USERNAME: "changeme"
      MONGO_PASSWORD: "changeme"
      MONGO_HOST: "changeme"
      MONGO_PORT: "changeme"
      MONGO_DB: "changeme"
      STOCK_WARNING_TRESHOLD: "5"
      MAIL_SERVER: "smtp.gmail.com"
      MAIL_PORT: "587"
      MAIL_USE_TLS: "True"
      MAIL_USERNAME: "changeme@gmail.com"
      MAIL_PASSWORD: "changeme"
      MAIL_DEFAULT_SENDER: "changeme"
      ENABLE_MEDICINE_CHECKER: "True"
      MEDICINE_CHECK_INTERVAL: "3"
      LOG_TYPE: "STDOUT"
      LOG_DIR: "logs"
      LOG_FILE: "app.log"
      LOG_MAX_BYTES: "10240"
      LOG_BACKUP_COUNT: "5"
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "changeme"
      MONGO_INITDB_ROOT_PASSWORD: "changeme"
      MONGO_INITDB_DATABASE: "changeme"
    ports:
      - "27017:27017"
    volumes:
      - ./docker_volumes/mongodb_data:/data/db
      - ./docker/components/mongo/init-mongo.sh:/tmp/init-mongo.sh:ro
    command: ["/bin/bash", "/tmp/init-mongo.sh", "docker-entrypoint.sh", "mongod"]